# This rule is not used by the project managed-redis-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to redis.redis-youjin.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: managed-redis-controller
    app.kubernetes.io/managed-by: kustomize
  name: managedredis-viewer-role
rules:
- apiGroups:
  - redis.redis-youjin.com
  resources:
  - managedredis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.redis-youjin.com
  resources:
  - managedredis/status
  verbs:
  - get
