apiVersion: redis.redis-youjin.com/v1
kind: ManagedRedis
metadata:
  name: redis-sample
  namespace: default
spec:
  version: "7.0"           # Redis 버전
  replicas: 3              # 인스턴스 수 (Primary + Replica)
  mode: REPLICATION        # 운영 모드: SINGLE, REPLICATION, CLUSTER
